### PR TITLE
Add Chart.js

### PR DESCRIPTION
**Pull request by AryanAhadinia**

### CODE REVIEW

**Review by mostafaghadimi — COMMENTED** [review]
Well done Aryan! 
Please remove `.idea` directory and then push the final commit to merge with the master branch.

**Review by mostafaghadimi — COMMENTED** [review]
Well done!

**Comment by AryanAhadinia** [comment]
Thank you!

**Comment by farbodhma** [comment]
https://github.com/farbodhma/chart-js

**Pull request merged**
