### PR TITLE
[Docker] [Dev] added examples of using docker + more explanation about docker-compose

### PR DESCRIPTION
**Pull request by AmooHashem**
By Saee Saadat, Arman Mohammadi and Seyyed Alireza Hashemi

### CODE REVIEW

**Review by mostafaghadimi — COMMENTED** [review]
Dear guys,

Please consider the following tips for merging the pull request:

1. The topic not covered properly and it is almost about the running the sample project. More contribution is needed for completing the docker or docker-compose documentation.
 
2. Some commit formats are invalid.

3. Node_modules folder should not be uploaded itself, place it in .gitignore file.

Thanks,
Mostafa

**Comment by AmooHashem** [comment]
سلام
مورد سوم رو حواسمون نبود.  درستش می‌کنیم.
در موردِ موردِ دوم هم نگفته بودین کامنتا باید فرمتِ خاصی داشته باشن، فقط گفته بودین که کامنتِ **نهایی** باید همچین فرمتی داشته باشه.
در موردِ موردِ اول هم باید بگم مستندی که از قبل موجود بود، تقریبا تمام مواردِ ابتداییِ داکر رو به خوبی پوشش می‌داد و ما برای این که بتونیم این مستند رو توسعه بدیم، دیدیم به نظرمون خوبه که بیایم با مثال توضیح بدیم. و مثلا خودم سر این داکر-کامپوز سعی کردم واقعا کیفیت مطالب رو بهتر کنم، تا کمیتشون رو.

**Comment by mostafaghadimi** [comment]
Dear @AmooHashem,

1. I do agree with you, the previous version of documentation was almost complete. You can add more details to few topics, like docker-swarm, network, etc. 

2. Would you please give a reference? In the documentation and readme, commit formats are defined.

3. It shouldn’t be placed at any commits. Another PR should be created.

**PS** In case of any ambiguity, feel free contacting me.

Thanks,
Mostafa

**Comment by mostafaghadimi** [comment]
Dear @AmooHashem,

I have checked what I have written in main `README` of the repo. 
Yeah you were right. The text wasn't clear. 
I'm so sorry. I will revise it once again.

Thanks for your feedback.

**Review by mostafaghadimi — COMMENTED** [review]
Well done guys!

Raise your names in the readme file.

**Pull request merged**
